import { ArrowLeft, ExternalLink, Eye, Heart, Plus, Sparkles } from "lucide-react";
import { Link, useRoute } from "wouter";
import { lazy, Suspense, useEffect, useMemo } from "react";
import { useFavorites } from "@/hooks/useFavorites";
import { trpc } from "@/lib/trpc";
import { getOptionDisplay } from "@/lib/optionDisplay";
import { collapsePriceHistoryToDailyLow, getLowestPrice, getRecentSoldOutObservations, mergeAllPriceHistory } from "@/lib/priceHistory";
import { createCoupangSearchUrl } from "@/lib/coupangSearchUrl";
import { hasCollectorVerifiedPurchasePath } from "@/lib/collectorVerifiedPurchase";
import { getProductMetaTags } from "@/lib/productMeta";
import { getProductDisplayName, getProductOptionDisplayLabel } from "@/lib/productDisplayName";
import { getOptimizedProductImageUrl } from "@/lib/optimizedImage";

const PriceHistoryChart = lazy(() => import("@/components/PriceHistoryChart"));

const won = (value: number) => `${new Intl.NumberFormat("ko-KR").format(value)}원`;

export default function ProductDetail() {
  const [, params] = useRoute("/product/:id");
  const productId = Number(params?.id ?? 0);
  const input = useMemo(() => ({ productId }), [productId]);
  const detail = trpc.catalog.product.useQuery(input, { enabled: Number.isInteger(productId) && productId > 0 });
  const auth = trpc.auth.me.useQuery();
  const userConfirmedPrices = trpc.userPrices.listForProduct.useQuery(input, { enabled: auth.data?.loginMethod === "google" && Number.isInteger(productId) && productId > 0 });
  const collectedPrices = trpc.catalog.collectedPriceHistory.useQuery(input, { enabled: Number.isInteger(productId) && productId > 0 });
  const markViewed = trpc.catalog.markViewed.useMutation();
  const related = trpc.catalog.relatedVariants.useQuery(input, { enabled: Number.isInteger(productId) && productId > 0 });
  const { favoriteIds, toggleProduct } = useFavorites();

  useEffect(() => {
    if (Number.isInteger(productId) && productId > 0) markViewed.mutate({ productId });
  }, [productId]);

  if (detail.isLoading) return <p className="py-24 text-center text-sm text-[#829184]">상품 정보를 불러오는 중입니다.</p>;
  if (!detail.data) return <p className="py-24 text-center text-sm text-[#829184]">상품을 찾을 수 없습니다.</p>;
  const { product, history } = detail.data;
  const collectedHistory = collectedPrices.data ?? [];
  const recentObservationCount = collectedHistory.length;
  const pricedCollectedHistory = collectedHistory.filter((point): point is typeof point & { price: number } => typeof point.price === "number" && Number.isSafeInteger(point.price) && point.price > 0);
  const recentSoldOutObservations = getRecentSoldOutObservations(collectedHistory);
  const mergedHistory = mergeAllPriceHistory(history, userConfirmedPrices.data ?? [], pricedCollectedHistory);
  const dailyLowestHistory = collapsePriceHistoryToDailyLow(mergedHistory);
  const chartData = dailyLowestHistory.map(point => ({ date: point.occurredAt.toLocaleDateString("ko-KR", { month: "numeric", day: "numeric" }), price: point.price }));
  const lowestPrice = getLowestPrice(dailyLowestHistory, product.lowestPrice);
  const variants = [product, ...(related.data ?? [])];
  const unitPrices = variants.flatMap(item => item.unitPrice === null ? [] : [item.unitPrice]);
  const bestUnitPrice = unitPrices.length > 0 ? Math.min(...unitPrices) : null;
  const latestUserConfirmedPrice = userConfirmedPrices.data?.[0];
  const metaTags = getProductMetaTags(product.variantLabel, product.unitLabel, product.name);
  const displayName = getProductDisplayName(product.name, product.variantLabel, product.unitLabel);
  const optionDisplayLabel = getProductOptionDisplayLabel(product.variantLabel, product.unitLabel);
  const hasCollectorVerifiedPath = hasCollectorVerifiedPurchasePath(product);
  const needsPurchaseFallback = (product.deepLinkStatus === "failed" || product.refreshState === "awaiting_collection") && !hasCollectorVerifiedPath;
  const coupangSearchUrl = createCoupangSearchUrl(product.name);

  return (
    <section>
      <div className="mb-5 flex items-center justify-between"><Link href="/" className="grid size-10 place-items-center rounded-full bg-white text-[#36543e] shadow-sm ring-1 ring-[#e2ebe1]"><ArrowLeft className="size-4" /></Link><button type="button" onClick={() => toggleProduct(product.id)} className={`grid size-10 place-items-center rounded-full shadow-sm ring-1 ${favoriteIds.has(product.id) ? "bg-[#176b3a] text-white ring-[#176b3a]" : "bg-white text-[#526956] ring-[#e2ebe1]"}`}><Heart className={`size-4 ${favoriteIds.has(product.id) ? "fill-current" : ""}`} /></button></div>
      <div className="rounded-3xl bg-white p-5 shadow-[0_8px_28px_rgba(35,71,43,.07)] ring-1 ring-[#e9efea]">
        <div className="flex gap-4"><div className="grid size-25 shrink-0 place-items-center overflow-hidden rounded-2xl bg-[#f4f7f3]"><img src={getOptimizedProductImageUrl(product.imageUrl, 200)} alt="" width={100} height={100} className="size-full object-contain p-2" decoding="async" /></div><div className="min-w-0"><span className="inline-flex rounded-md bg-[#e5f2e7] px-2 py-1 text-[10px] font-bold text-[#176b3a]">{product.source === "goldbox" ? "골드박스" : "가격 추적"}</span><h1 className="mt-2 text-[16px] font-bold leading-6 tracking-[-0.045em] text-[#25362a]">{displayName}</h1></div></div>
        <div className="mt-6 grid grid-cols-2 divide-x divide-[#e9efea] rounded-2xl bg-[#f7faf7] py-3"><div className="px-4"><p className="text-[11px] font-semibold text-[#778679]">현재가</p><strong className={`mt-1 block text-xl tracking-[-0.06em] ${product.inStock ? "text-[#25362a]" : "text-[#8a5a20]"}`}>{product.inStock ? won(product.currentPrice) : "품절"}</strong></div><div className="px-4"><p className="text-[11px] font-semibold text-[#778679]">90일 최저가</p><strong className="mt-1 block text-xl tracking-[-0.06em] text-[#118245]">{won(lowestPrice)}</strong></div></div>
        {!product.inStock ? <div className="mt-3 flex items-start gap-2 rounded-2xl border border-[#f0d9b4] bg-[#fff8ec] px-4 py-3 text-[#805b25]"><span className="mt-0.5 inline-flex rounded-full bg-[#f1c982] px-2 py-0.5 text-[10px] font-extrabold">품절</span><div><p className="text-xs font-extrabold">현재 품절로 확인된 상품입니다.</p><p className="mt-1 text-[10px] leading-4 text-[#987642]">마지막 가격은 참고용으로 유지하며, 재입고 관측 전까지 현재가로 갱신하지 않습니다.</p></div></div> : null}
        <div className="mt-3 rounded-2xl border border-[#e8efe8] bg-white px-4 py-3"><p className="text-[10px] font-bold text-[#638169]">현재 추적 구성</p><div className="mt-1 flex items-baseline justify-between gap-3">{optionDisplayLabel ? <strong className="text-sm tracking-[-0.03em] text-[#213825]">{optionDisplayLabel}</strong> : <span />}{product.unitPrice && product.unitLabel ? <span className="shrink-0 text-xs font-bold text-[#176b3a]">{product.unitLabel}당 {won(product.unitPrice)}</span> : null}</div>{metaTags.capacity || metaTags.packSize || metaTags.quantity ? <div className="mt-2 flex flex-wrap gap-1.5">{metaTags.capacity ? <span className="rounded-full bg-[#e7f3e9] px-2 py-1 text-[10px] font-bold text-[#176b3a]">용량 {metaTags.capacity}</span> : null}{metaTags.packSize ? <span className="rounded-full bg-[#fff3df] px-2 py-1 text-[10px] font-bold text-[#9a6415]">포장 {metaTags.packSize}</span> : null}{metaTags.quantity ? <span className="rounded-full bg-[#eef4ff] px-2 py-1 text-[10px] font-bold text-[#3567a8]">수량 {metaTags.quantity}</span> : null}</div> : null}<p className="mt-1 text-[10px] leading-4 text-[#869387]">용량·포장 단위·수량·구성이 다른 옵션은 별도의 상품으로 가격을 추적합니다.</p></div>
        {latestUserConfirmedPrice ? <div className="mt-3 rounded-2xl border border-[#eadfbd] bg-[#fffaf0] px-4 py-3"><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-bold text-[#9a6a16]">최근 확인 가격</p></div><div className="mt-1 flex items-baseline justify-between gap-3"><strong className="text-lg tracking-[-0.04em] text-[#6f5214]">{won(latestUserConfirmedPrice.price)}</strong><span className="text-[10px] text-[#887950]">{new Date(latestUserConfirmedPrice.checkedAt).toLocaleString("ko-KR", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" })} 확인</span></div><p className="mt-1 text-[10px] leading-4 text-[#887950]">최근 확인한 가격과 확인 시각입니다.</p></div> : null}
      </div>
      <div className="mt-5 rounded-3xl bg-white p-5 shadow-[0_8px_28px_rgba(35,71,43,.07)] ring-1 ring-[#e9efea]"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold text-[#308154]">PRICE HISTORY</p><h2 className="mt-1 text-lg font-extrabold tracking-[-0.055em]">가격 이력</h2></div><span className="inline-flex items-center gap-1 rounded-full bg-[#e5f2e7] px-2.5 py-1 text-[10px] font-bold text-[#176b3a]"><Sparkles className="size-3" />90일</span></div><div className="mb-4 rounded-2xl bg-[#f2f8f3] px-4 py-3"><div className="flex items-center justify-between gap-3"><p className="text-[10px] font-bold text-[#5f7765]">역대최저가 대비 현재가</p><span className="shrink-0 text-[10px] font-bold text-[#5f7765]">최근 관측 {recentObservationCount.toLocaleString("ko-KR")}회</span></div><p className="mt-1 text-sm font-extrabold text-[#176b3a]">현재 {won(product.currentPrice)} · 역대최저 {won(product.lowestPrice)}</p><p className="mt-1 text-[10px] leading-4 text-[#708075]">{product.currentPrice <= product.lowestPrice ? "현재가가 역대최저가와 같습니다." : `역대최저가보다 ${won(product.currentPrice - product.lowestPrice)} 높습니다.`}</p></div>
        {chartData.length === 0 ? <p className="flex h-55 items-center justify-center text-sm text-[#829184]">가격 이력이 쌓이면 차트가 표시됩니다.</p> : <Suspense fallback={<div className="flex h-55 items-center justify-center text-sm text-[#829184]">가격 이력 차트를 준비하는 중입니다.</div>}><PriceHistoryChart data={chartData} /></Suspense>}
        {dailyLowestHistory.length || recentSoldOutObservations.length ? <div className="mt-4 rounded-2xl border border-[#e8efe8] bg-[#fbfdfb] px-3 py-3"><p className="text-[10px] font-bold text-[#487452]">최근 가격·재고 이력</p><p className="mt-1 text-[10px] leading-4 text-[#718071]">가격은 날짜별 최저가로, 품절은 수집기가 확인한 시각으로 표시합니다.</p>{recentSoldOutObservations.length ? <div className="mt-2 rounded-xl border border-[#f0dfc2] bg-[#fffaf0] px-2.5"><p className="py-2 text-[10px] font-bold text-[#8a6225]">품절 확인 이력</p><div className="divide-y divide-[#f3e7d3]">{recentSoldOutObservations.map((point, index) => <div key={`${point.productId}-${point.occurredAt.getTime()}-${index}`} className="flex items-center justify-between gap-3 py-2 text-[11px]"><div className="min-w-0"><span className="font-extrabold text-[#8a6225]">품절</span>{point.optionName ? <span className="ml-1.5 truncate text-[10px] text-[#997d4b]">{point.optionName}</span> : null}</div><div className="shrink-0 text-right"><p className="font-bold text-[#80602b]">{point.price ? `참고 ${won(point.price)}` : "가격 미제공"}</p><p className="mt-0.5 text-[9px] text-[#aa9164]">{point.occurredAt.toLocaleString("ko-KR", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" })}</p></div></div>)}</div></div> : null}{dailyLowestHistory.length ? <div className="mt-3 divide-y divide-[#edf1ed]">{dailyLowestHistory.slice(-5).reverse().map(point => <div key={point.key} className="flex items-center justify-between gap-3 py-2 text-[11px]"><span className="min-w-0 truncate text-[#68796b]">{point.occurredAt.toLocaleDateString("ko-KR", { month: "numeric", day: "numeric" })}</span><strong className="text-[#245f34]">{won(point.price)}</strong></div>)}</div> : null}</div> : null}
      </div>
      {variants.length > 1 ? <section className="mt-5 overflow-hidden rounded-3xl bg-white shadow-[0_8px_28px_rgba(35,71,43,.07)] ring-1 ring-[#e9efea]"><div className="flex items-center justify-between px-5 pb-2 pt-5"><div><p className="text-xs font-bold text-[#308154]">SAME PRODUCT FAMILY</p><h2 className="mt-1 text-lg font-extrabold tracking-[-0.055em]">다른 옵션 보기</h2></div><span className="rounded-full bg-[#e5f2e7] px-2.5 py-1 text-[10px] font-bold text-[#176b3a]">{variants.length}개 구성</span></div><div className="divide-y divide-[#edf1ed]">{variants.map(option => { const isCurrent = option.id === product.id; const isBestValue = option.unitPrice !== null && option.unitPrice === bestUnitPrice; const saved = favoriteIds.has(option.id); const display = getOptionDisplay(option); return <div key={option.id} role={isCurrent ? undefined : "link"} tabIndex={isCurrent ? undefined : 0} onClick={() => { if (!isCurrent) window.location.assign(`/product/${option.id}`); }} onKeyDown={event => { if (!isCurrent && (event.key === "Enter" || event.key === " ")) window.location.assign(`/product/${option.id}`); }} className={`flex items-center gap-3 px-5 py-4 ${isCurrent ? "" : "cursor-pointer transition hover:bg-[#f8fbf8]"}`}><div className="grid size-13 shrink-0 place-items-center overflow-hidden rounded-xl bg-[#f4f7f3]"><img src={getOptimizedProductImageUrl(option.imageUrl, 104)} alt="" width={52} height={52} className="size-full object-contain p-1.5" loading="lazy" decoding="async" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5">{isCurrent ? <span className="inline-flex items-center gap-1 text-[10px] font-bold text-[#176b3a]"><Eye className="size-3" />보고 있는 구성</span> : <span className="text-[10px] font-medium text-[#829184]">눌러서 옵션 상세 보기</span>}{isBestValue ? <span className="rounded bg-[#e5f2e7] px-1.5 py-0.5 text-[9px] font-bold text-[#176b3a]">최저 단위가</span> : null}</div><p className="mt-1 text-sm font-extrabold tracking-[-0.04em] text-[#26382a]">{display.label}</p>{display.showProductName ? <p className="mt-0.5 line-clamp-1 text-[10px] text-[#7c8a7e]">{option.name}</p> : null}<p className="mt-1 text-base font-extrabold tracking-[-0.05em]">{won(option.currentPrice)} <span className={`ml-1 ${option.unitPrice !== null && option.unitLabel ? "text-xs font-medium text-[#758577]" : "text-[10px] font-medium text-[#8b988d]"}`}>{display.unitText}</span></p></div>{isCurrent ? <span className="grid size-9 place-items-center rounded-full bg-[#e5f2e7] text-[#176b3a]"><Eye className="size-4" /></span> : <button type="button" onClick={event => { event.stopPropagation(); toggleProduct(option.id); }} aria-label={`${display.label} 찜하기`} className={`grid size-9 place-items-center rounded-full transition active:scale-95 ${saved ? "bg-[#176b3a] text-white" : "bg-[#e5f2e7] text-[#176b3a]"}`}>{saved ? <Heart className="size-4 fill-current" /> : <Plus className="size-5" />}</button>}</div>; })}</div></section> : null}
      {!auth.data ? <div className="mt-5 rounded-2xl border border-[#cfe7d3] bg-[#f2faf3] p-4"><p className="text-sm font-extrabold text-[#176b3a]">가격이 내려가면 바로 알려드릴까요?</p><p className="mt-1 text-[11px] leading-4 text-[#62806a]">카카오 로그인 후 상품을 찜하면 이메일 또는 앱 알림으로 가격 변동을 알려드립니다.</p><a href={`/api/auth/kakao?returnTo=${encodeURIComponent(`/product/${product.id}`)}`} className="mt-3 flex h-11 items-center justify-center rounded-xl bg-[#fee500] text-sm font-extrabold text-[#191600] active:scale-[.98]">카카오로 로그인하고 가격 알림 받기</a></div> : null}
      {needsPurchaseFallback ? <div className="mt-5 rounded-2xl border border-[#f0ddbf] bg-[#fffaf1] p-4 text-center"><p className="text-sm font-extrabold text-[#7b581d]">판매 상태 확인 필요</p><p className="mt-1 text-[11px] leading-4 text-[#8b7449]">기존 옵션 SKU가 쿠팡 공식 결과에서 확인되지 않아 구매 링크를 숨겼습니다.</p><a href={coupangSearchUrl} target="_blank" rel="noopener noreferrer" className="mt-3 flex h-11 items-center justify-center gap-2 rounded-xl bg-[#176b3a] text-sm font-extrabold text-white active:scale-[.98]">쿠팡에서 같은 상품 검색 <ExternalLink className="size-4" /></a></div> : product.deepLinkUrl ? <a href={product.deepLinkUrl} target="_blank" rel="noopener noreferrer" className="mt-5 flex h-13 items-center justify-center gap-2 rounded-2xl bg-[#176b3a] text-sm font-extrabold text-white shadow-[0_12px_24px_rgba(23,107,58,.21)] active:scale-[.98]">쿠팡에서 상품 보기 <ExternalLink className="size-4" /></a> : hasCollectorVerifiedPath ? <div className="mt-5"><p className="mb-2 text-center text-[10px] font-semibold text-[#607765]">수집기가 최근 확인한 정확 옵션 상품 경로입니다. 제휴 딥링크는 생성 대기 중입니다.</p><a href={product.affiliateUrl!} target="_blank" rel="noopener noreferrer" className="flex h-13 items-center justify-center gap-2 rounded-2xl bg-[#176b3a] text-sm font-extrabold text-white shadow-[0_12px_24px_rgba(23,107,58,.21)] active:scale-[.98]">쿠팡에서 상품 보기 <ExternalLink className="size-4" /></a></div> : <div className="mt-5 flex h-13 flex-col items-center justify-center rounded-2xl bg-[#dfe9e1] text-xs font-bold text-[#55715d]"><span>딥링크 준비 중</span><span className="mt-0.5 text-[10px] font-medium">준비가 완료되면 구매할 수 있습니다.</span></div>}
    </section>
  );
}
