export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  gmailSmtpUsername: process.env.GMAIL_SMTP_USERNAME?.trim() ?? "",
  gmailSmtpAppPassword: process.env.GMAIL_SMTP_APP_PASSWORD?.replace(/\s/g, "") ?? "",
  gasynCollectToken: process.env.GASYN_COLLECT_TOKEN?.trim() ?? "",
  gasynExternalScheduleToken: process.env.GASYN_EXTERNAL_SCHEDULE_TOKEN?.trim() ?? "",
  kakaoRestApiKey: process.env.KAKAO_REST_API_KEY?.trim() ?? "",
  kakaoClientSecret: process.env.KAKAO_CLIENT_SECRET?.trim() ?? "",
  webPushVapidPublicKey: process.env.VITE_WEB_PUSH_VAPID_PUBLIC_KEY?.trim() ?? "",
  webPushVapidPrivateKey: process.env.WEB_PUSH_VAPID_PRIVATE_KEY?.trim() ?? "",
  webPushVapidSubject: process.env.WEB_PUSH_VAPID_SUBJECT?.trim() ?? "",
  appBaseUrl: (process.env.APP_BASE_URL ?? "https://gasyntrack-g9qvfrnc.manus.space").replace(/\/$/, ""),
};
